Fix HTTP 200 error setting non-string task points via Conduit API
Summary:
Do not require strings but allow scalars when setting task points.

```
EXCEPTION: (InvalidArgumentException) Call to phutil_nonempty_string() expected null or a string, got: float. at [<arcanist>/src/utils/utils.php:2121]
  #0 <#2> phutil_nonempty_string(double) called at [<phorge>/src/applications/maniphest/xaction/ManiphestTaskPointsTransaction.php:85]
```
Closes T16262

Test Plan:
* Have points enabled via http://phorge.localhost/config/edit/maniphest.points/
* Run `echo '{"transactions": [{"type": "points", "value":13}, {"type": "comment", "value":"Setting points!"}],"objectIdentifier":"T1234"}' | /var/www/html/phorge/arcanist/bin/arc call-conduit --conduit-uri http://phorge.localhost --conduit-token "cli-whatever" maniphest.edit --`

Reviewers: O1 Blessed Committers, valerio.bozzolan

Reviewed By: O1 Blessed Committers, valerio.bozzolan

Subscribers: tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16262

Differential Revision: https://we.phorge.it/D26337