Throw a proper ConduitException when trying to create an empty diff
Summary:
Avoid an ugly RuntimeException when trying to create an empty diff by bailing out early with a proper error message.
(If we were to only check if $change_data is null, we'd still end up with an empty revision created.)

```
EXCEPTION: (RuntimeException) foreach() argument must be of type array|object, null given at [<arcanist>/src/error/PhutilErrorHandler.php:270]
```

Closes T16427

Test Plan:
* PHP 8.5
* Go to http://phorge.localhost/conduit/method/differential.creatediff/
* Press the "Call Method" button

Reviewers: O1 Blessed Committers, mainframe98

Reviewed By: O1 Blessed Committers, mainframe98

Subscribers: mainframe98, tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16427

Differential Revision: https://we.phorge.it/D26638