Fix "expected null or a string, got: int" on Jupyter Notebook
Summary:
The value needs to be an integer per specification and per the next check in the code.
Previous rPb08c7c761c1078658da02ba68fcb4b0f67912438 was not fully correct.

```
EXCEPTION: (InvalidArgumentException) Call to phutil_nonempty_string() expected null or a string, got: int. at [<arcanist>/src/utils/utils.php:2121]
  #0 <#2> phutil_nonempty_string(integer) called at [<phorge>/src/applications/files/document/PhabricatorJupyterDocumentEngine.php:326]
```

Fixes T16312

Test Plan:
* Go to http://phorge.localhost/file/upload/
* Upload a valid JSON text file: `{"nbformat": 0, "nbformat_minor": 5, "metadata": {}, "cells": []}`
* On resulting http://phorge.localhost/F1, select "View Options > View as Jupyter Notebook"

Reviewers: O1 Blessed Committers, mainframe98

Reviewed By: O1 Blessed Committers, mainframe98

Subscribers: mainframe98, tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16312

Differential Revision: https://we.phorge.it/D26435