Handle dashboard panel configuration being null more gracefully
Summary:
Get a little bit closer to rendering the Phorge frontpage with PHP strict typing enabled.
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict

```
EXCEPTION: (TypeError) json_decode(): Argument #1 ($json) must be of type string, null given at [<arcanist>/src/utils/utils.php:1338]
  #0 <#2> json_decode(NULL, boolean) called at [<arcanist>/src/utils/utils.php:1338]
  #1 <#2> phutil_json_decode(NULL) called at [<phorge>/src/applications/dashboard/paneltype/PhabricatorDashboardTabsPanelType.php:37]

EXCEPTION: (TypeError) ipull(): Argument #1 ($list) must be of type array, null given, called in /var/www/html/phorge/phorge/src/applications/dashboard/paneltype/PhabricatorDashboardTabsPanelType.php on line 64 at [<arcanist>/src/utils/utils.php:281]
  #0 <#2> ipull(NULL, string) called at [<phorge>/src/applications/dashboard/paneltype/PhabricatorDashboardTabsPanelType.php:64]
  #1 <#2> PhabricatorDashboardTabsPanelType::renderPanelContent(PhabricatorUser, PhabricatorDashboardPanel, PhabricatorDashboardPanelRenderingEngine) called at [<phorge>/src/applications/dashboard/engine/PhabricatorDashboardPanelRenderingEngine.php:175]

EXCEPTION: (TypeError) array_keys(): Argument #1 ($array) must be of type array, null given at [<phorge>/src/applications/dashboard/paneltype/PhabricatorDashboardTabsPanelType.php:93]
  #0 <#2> array_keys(NULL) called at [<phorge>/src/applications/dashboard/paneltype/PhabricatorDashboardTabsPanelType.php:93]
  #1 <#2> PhabricatorDashboardTabsPanelType::renderPanelContent(PhabricatorUser, PhabricatorDashboardPanel, PhabricatorDashboardPanelRenderingEngine) called at [<phorge>/src/applications/dashboard/engine/PhabricatorDashboardPanelRenderingEngine.php:175]

EXCEPTION: (RuntimeException) foreach() argument must be of type array|object, null given at [<arcanist>/src/error/PhutilErrorHandler.php:271]
  #0 <#2> PhutilErrorHandler::handleError(integer, string, string, integer) called at [<phorge>/src/applications/dashboard/paneltype/PhabricatorDashboardTabsPanelType.php:275]
  #1 <#2> PhabricatorDashboardTabsPanelType::renderPanelContent(PhabricatorUser, PhabricatorDashboardPanel, PhabricatorDashboardPanelRenderingEngine) called at [<phorge>/src/applications/dashboard/engine/PhabricatorDashboardPanelRenderingEngine.php:175]
```

Refs T16725

Test Plan: Insert `declare( strict_types = 1 );` into all Arcanist PHP files; apply D27125 in Phorge; invert the `if ($console)` condition in Phorge's `PhabricatorStandardPageView::willSendResponse()`; succeed in getting the Phorge frontpage rendered which has no dashboard panels etc configured.

Reviewers: O1 Blessed Committers, avivey

Reviewed By: O1 Blessed Committers, avivey

Subscribers: avivey, tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16725

Differential Revision: https://we.phorge.it/D27127