Handle some incorrect variable types
Summary:
Get a little bit closer to rendering the Phorge frontpage with PHP strict typing enabled.
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict

```
EXCEPTION: (TypeError) strlen(): Argument #1 ($string) must be of type string, false given at [<phorge>/src/infrastructure/storage/lisk/PhabricatorLiskDAO.php:43]
EXCEPTION: (TypeError) strlen(): Argument #1 ($string) must be of type string, PhutilQueryString given at [<phorge>/src/infrastructure/query/PhabricatorQuery.php:91]
EXCEPTION: (TypeError) htmlspecialchars(): Argument #1 ($string) must be of type string, int given at [<phorge>/src/infrastructure/markup/render.php:145]
EXCEPTION: (TypeError) htmlspecialchars(): Argument #1 ($string) must be of type string, true given at [<phorge>/src/infrastructure/markup/render.php:147]
```

Refs T16725

Test Plan: Insert `declare( strict_types = 1 );` into all Phorge PHP files (not Arcanist); invert the `if ($console)` condition in `PhabricatorStandardPageView::willSendResponse()`, succeed in getting the Phorge frontpage rendered which has no dashboard panels etc configured.

Reviewers: O1 Blessed Committers, avivey

Reviewed By: O1 Blessed Committers, avivey

Subscribers: mainframe98, avivey, tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16725

Differential Revision: https://we.phorge.it/D27125