Conduit: Validate that "attachments" parameter is an array
Summary:
Do the same dance as for "constraints" a few lines earlier.

```
EXCEPTION: (RuntimeException) array_keys() expects parameter 1 to be array, string given at [<arcanist>/src/error/PhutilErrorHandler.php:270]
  #1 <#2> array_keys(string) called at [<phorge>/src/applications/search/engine/PhabricatorApplicationSearchEngine.php:1280]
```

Closes T16395

Test Plan: Unknown.

Reviewers: O1 Blessed Committers, mainframe98

Reviewed By: O1 Blessed Committers, mainframe98

Subscribers: pppery, tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16395

Differential Revision: https://we.phorge.it/D26584